#!/bin/bash
. "$(dirname "$0")/common"
. "$(dirname "$0")/defaults"
. "$(dirname "$0")/enshrouded-bootstrap-shared"

main() {
  info "Running enshrouded-bootstrap"
  prepareEnshroudedAppFolders
  updateOrCreateEnshroudedServerConfig
  prepareSteamA2sPythonLibrary

  # no proton bootstrap needed

  initCrontab
  supervisorctl start enshrouded-updater
  info "Bootstrap complete"
}

main
