#!/bin/bash
. "$(dirname "$0")/common"
. "$(dirname "$0")/defaults"

enshrouded_server_pid=-1
timeout=60
kill_signal=TERM

cd "$install_path" || fatal "Could not cd $install_path"
enshrouded_server="$install_path/$enshrouded_binary_path"

main() {
  waitForServerDownload
  runServer
}

waitForServerDownload() {
  while :; do
    if [ -f "$enshrouded_server" ]; then
      break
    else
      debug "enshrouded Server is not yet downloaded - waiting"
      sleep 7
    fi
  done
}

runServer() {
  info "Running enshrouded-server"
  debug "Server config ServerName:$SERVER_NAME - ServerPort:${SERVER_PORT:-15636} - ServerQueryPort:${SERVER_QUERYPORT:-15637}"

  export WINEDEBUG=$WINEDEBUG
  export WINEDLLPATH="/usr/local/bin/files/lib64//wine:/usr/local/bin/files/lib//wine"
  export LD_LIBRARY_PATH="/usr/local/bin/files/lib64/:/usr/local/bin/files/lib/"
  export WINEPREFIX="$install_path/steamapps/compatdata/$steam_app_id/pfx/"
  export WINEESYNC="1"
  export WINEFSYNC="1"
  export WINEDLLOVERRIDES="steam.exe=b;dotnetfx35.exe=b;dotnetfx35setup.exe=b;beclient.dll=b,n;beclient_x64.dll=b,n;d3d11=n;d3d10core=n;d3d9=n;dxgi=n;d3d12=n;d3d12core=n"
  export STEAM_COMPAT_CLIENT_INSTALL_PATH="/home/enshrouded/.steam/steam"
  export WINE_LARGE_ADDRESS_AWARE="1"
  export GST_PLUGIN_SYSTEM_PATH_1_0="/usr/local/bin/files/lib64/gstreamer-1.0:/usr/local/bin/files/lib/gstreamer-1.0"
  export WINE_GST_REGISTRY_DIR="$install_path/steamapps/compatdata/$steam_app_id/gstreamer-1.0/"

  chmod +x "$enshrouded_server"
  /usr/local/bin/files/bin/wine64 "$enshrouded_server" &
  enshrouded_server_pid=$!
  echo $enshrouded_server_pid >"$enshrouded_server_pidfile"

  wait $enshrouded_server_pid
  debug "enshrouded-server with PID $enshrouded_server_pid stopped"

  cleanup
  info "Shutdown complete"
  exit 0
}

cleanup() {
  clearLock "$enshrouded_server_pidfile"
}

shutdown() {
  debug "Received signal to shut down enshrouded-server"
  if [ $enshrouded_server_pid -eq -1 ]; then
    debug "enshrouded server is not running yet - aborting startup"
    exit
  fi
  info "Shutting down enshrouded server with PID $enshrouded_server_pid"
  kill -TERM $enshrouded_server_pid
  shutdown_timeout=$(($(date +%s) + timeout))
  while [ -d "/proc/$enshrouded_server_pid" ]; do
    if [ "$(date +%s)" -gt $shutdown_timeout ]; then
      shutdown_timeout=$(($(date +%s) + timeout))
      warn "Timeout while waiting for server to shut down - sending SIG$kill_signal to PID $enshrouded_server_pid"
      kill -$kill_signal $enshrouded_server_pid
      case "$kill_signal" in
      INT)
        kill_signal=TERM
        ;;
      *)
        kill_signal=KILL
        ;;
      esac
    fi
    debug "Waiting for enshrouded Server with PID $enshrouded_server_pid to shut down"
    sleep 6
  done
}

trap shutdown SIGINT SIGTERM
main
