#!/bin/bash
. "$(dirname "$0")/common"
. "$(dirname "$0")/defaults"

main() {
  info "Force Enshrouded update"
  rm -f $version_file_path

  # Remove steamapp manifests to solve steamcmd update issues #119
  debug "Removing $install_path/$manifest"
  rm -f $install_path/$manifest

  supervisorctl start enshrouded-updater
}

main
