#!/bin/bash
. "$(dirname "$0")/common"
. "$(dirname "$0")/defaults"

prepareEnshroudedAppFolders() {
  mkdir -p "$install_path"
}

initCrontab() {
  crontab=$(mktemp)

  if [ -n "$UPDATE_CRON" ]; then
    debug "creating cron for update checks (schedule: $UPDATE_CRON)"
    echo "$UPDATE_CRON supervisorctl start enshrouded-updater >/dev/null 2>&1" >>"$crontab"
  fi

  if [ -n "$BACKUP_CRON" ]; then
    debug "creating cron for backups (schedule: $BACKUP_CRON)"
    echo "$BACKUP_CRON supervisorctl start enshrouded-backup >/dev/null 2>&1" >>"$crontab"
  fi

  crontab "$crontab"
  rm -f "$crontab"
}

prepareSteamA2sPythonLibrary() {
  pip3 install python-a2s==1.3.0 --break-system-packages
}

bootstrapHook() {
  if [ -n "$BOOTSTRAP_HOOK" ]; then
    info "Running bootstrap hook: $BOOTSTRAP_HOOK"
    eval "$BOOTSTRAP_HOOK"
  fi
}

updateOrCreateEnshroudedServerConfig() {
  if [[ ! -e ${install_path}/enshrouded_server.json ]]; then
    mkdir -p ${install_path}
    touch ${install_path}/enshrouded_server.json

    # write json to file ${install_path}/enshrouded_server.json

    cat >${install_path}/enshrouded_server.json << EOF
{
  "name": "Enshrouded Server",
  "password": "",
  "saveDirectory": "./savegame",
  "logDirectory": "./logs",
  "ip": "0.0.0.0",
  "queryPort": 15637,
  "slotCount": 16
}
EOF
  fi

  if [[ -n "$SERVER_NAME" ]]; then
    echo "$(jq --arg name "$SERVER_NAME" '.name = $name' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_PASSWORD" ]]; then
    echo "$(jq --arg password "$SERVER_PASSWORD" '.password = $password' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_SAVE_DIR" ]]; then
    echo "$(jq --arg saveDirectory "$SERVER_SAVE_DIR" '.saveDirectory = $saveDirectory' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_LOG_DIR" ]]; then
    echo "$(jq --arg logDirectory "$SERVER_LOG_DIR" '.logDirectory = $logDirectory' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_IP" ]]; then
    echo "$(jq --arg ip "$SERVER_IP" '.ip = $ip' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_QUERYPORT" ]]; then
    echo "$(jq --argjson queryPort "$SERVER_QUERYPORT" '.queryPort = $queryPort' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_SLOT_COUNT" ]]; then
    echo "$(jq --argjson slotCount "$SERVER_SLOT_COUNT" '.slotCount = $slotCount' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  updateUserGroupConfig
  updateGameSettingsConfig
}

updateUserGroupConfig() {
  local group_count group_index group_param group_value
  # get largest group index of env vars
  group_count=$(compgen -A variable | grep -E "^SERVER_ROLE_[0-9]+_" | cut -d'_' -f3 | sort -nr | head -n1)

  # check if userGroups array exists if not create empty array
  if ! jq -e 'has("userGroups")' ${install_path}/enshrouded_server.json >/dev/null; then
    debug "userGroups array does not exist, creating empty array"
    echo "$(jq '.userGroups = []' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  # add missing groups
  for group_index in $(seq 0 $group_count); do
    if ! jq -e --argjson group_index "$group_index" '.userGroups | has($group_index)' ${install_path}/enshrouded_server.json >/dev/null; then
      debug "group $group_index does not exist, creating default group"
      echo "$(jq --argjson group_index "$group_index" '.userGroups += [{"name": "Default", "password": "", "canKickBan": false, "canAccessInventories": false, "canEditBase": false, "canExtendBase": false, "reservedSlots": 0}]' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
    fi
  done

  for i in $(compgen -A variable | grep -E "^SERVER_ROLE_[0-9]+_"); do
    group_index=$(echo $i | cut -d'_' -f3)
    group_param=$(echo $i | cut -d'_' -f4-)
    group_value=$(eval echo \$$i)

    case $group_param in
      NAME)
        debug "updating group $group_index name to $group_value"
        echo "$(jq --argjson group_index "$group_index" --arg name "$group_value" '.userGroups[$group_index].name = $name' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
        ;;
      PASSWORD)
        debug "updating group $group_index password to $group_value"
        echo "$(jq --argjson group_index "$group_index" --arg password "$group_value" '.userGroups[$group_index].password = $password' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
        ;;
      CAN_KICK_BAN)
        debug "updating group $group_index canKickBan to $group_value"
        echo "$(jq --argjson group_index "$group_index" --argjson canKickBan "$group_value" '.userGroups[$group_index].canKickBan = $canKickBan' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
        ;;
      CAN_ACCESS_INVENTORIES)
        debug "updating group $group_index canAccessInventories to $group_value"
        echo "$(jq --argjson group_index "$group_index" --argjson canAccessInventories "$group_value" '.userGroups[$group_index].canAccessInventories = $canAccessInventories' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
        ;;
      CAN_EDIT_BASE)
        debug "updating group $group_index canEditBase to $group_value"
        echo "$(jq --argjson group_index "$group_index" --argjson canEditBase "$group_value" '.userGroups[$group_index].canEditBase = $canEditBase' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
        ;;
      CAN_EXTEND_BASE)
        debug "updating group $group_index canExtendBase to $group_value"
        echo "$(jq --argjson group_index "$group_index" --argjson canExtendBase "$group_value" '.userGroups[$group_index].canExtendBase = $canExtendBase' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
        ;;
      RESERVED_SLOTS)
        debug "updating group $group_index reservedSlots to $group_value"
        echo "$(jq --argjson group_index "$group_index" --argjson reservedSlots "$group_value" '.userGroups[$group_index].reservedSlots = $reservedSlots' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
        ;;
    esac
  done
}

updateGameSettingsConfig() {
  if [[ -n "$SERVER_GS_PRESET" ]]; then
    debug "updating gameSettingsPreset to $SERVER_GS_PRESET"
    echo "$(jq --arg name "$SERVER_GS_PRESET" '.gameSettingsPreset = $name' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_PLAYER_HEALTH_FACTOR" ]]; then
    debug "updating gameSettingsPlayerHealthFactor to $SERVER_GS_PLAYER_HEALTH_FACTOR"
    echo "$(jq --argjson factor "$SERVER_GS_PLAYER_HEALTH_FACTOR" '.gameSettings.playerHealthFactor = $factor' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_PLAYER_MANA_FACTOR" ]]; then
    debug "updating gameSettingsPlayerManaFactor to $SERVER_GS_PLAYER_MANA_FACTOR"
    echo "$(jq --argjson factor "$SERVER_GS_PLAYER_MANA_FACTOR" '.gameSettings.playerManaFactor = $factor' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_PLAYER_STAMINA_FACTOR" ]]; then
    debug "updating gameSettingsPlayerStaminaFactor to $SERVER_GS_PLAYER_STAMINA_FACTOR"
    echo "$(jq --argjson factor "$SERVER_GS_PLAYER_STAMINA_FACTOR" '.gameSettings.playerStaminaFactor = $factor' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_PLAYER_BODY_HEAT_FACTOR" ]]; then
    debug "updating gameSettingsPlayerBodyHeatFactor to $SERVER_GS_PLAYER_BODY_HEAT_FACTOR"
    echo "$(jq --argjson factor "$SERVER_GS_PLAYER_BODY_HEAT_FACTOR" '.gameSettings.playerBodyHeatFactor = $factor' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_ENABLE_DURABILITY" ]]; then
    debug "updating gameSettingsEnableDurability to $SERVER_GS_ENABLE_DURABILITY"
    echo "$(jq --argjson bool "$SERVER_GS_ENABLE_DURABILITY" '.gameSettings.enableDurability = $bool' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_ENABLE_STARVING_DEBUFF" ]]; then
    debug "updating gameSettingsEnableStarvingDebuff to $SERVER_GS_ENABLE_STARVING_DEBUFF"
    echo "$(jq --argjson bool "$SERVER_GS_ENABLE_STARVING_DEBUFF" '.gameSettings.enableStarvingDebuff = $bool' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_FOOD_BUFF_DURATION_FACTOR" ]]; then
    debug "updating gameSettingsFoodBuffDurationFactor to $SERVER_GS_FOOD_BUFF_DURATION_FACTOR"
    echo "$(jq --argjson factor "$SERVER_GS_FOOD_BUFF_DURATION_FACTOR" '.gameSettings.foodBuffDurationFactor = $factor' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_FROM_HUNGER_TO_STARVING" ]]; then
    debug "updating gameSettingsFromHungerToStarving to $SERVER_GS_FROM_HUNGER_TO_STARVING"
    echo "$(jq --argjson factor "$SERVER_GS_FROM_HUNGER_TO_STARVING" '.gameSettings.fromHungerToStarving = $factor' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_SHROUD_TIME_FACTOR" ]]; then
    debug "updating gameSettingsShroudTimeFactor to $SERVER_GS_SHROUD_TIME_FACTOR"
    echo "$(jq --argjson factor "$SERVER_GS_SHROUD_TIME_FACTOR" '.gameSettings.shroudTimeFactor = $factor' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_ENABLE_GLIDER_TURBULENCES" ]]; then
    debug "updating gameSettingsEnableGliderTurbulences to $SERVER_GS_ENABLE_GLIDER_TURBULENCES"
    echo "$(jq --argjson bool "$SERVER_GS_ENABLE_GLIDER_TURBULENCES" '.gameSettings.enableGliderTurbulences = $bool' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_WEATHER_FREQUENCY" ]]; then
    debug "updating gameSettingsWeatherFrequency to $SERVER_GS_WEATHER_FREQUENCY"
    echo "$(jq --arg name "$SERVER_GS_WEATHER_FREQUENCY" '.gameSettings.weatherFrequency = $name' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_RANDOM_SPAWNER_AMOUNT" ]]; then
    debug "updating gameSettingsRandomSpawnerAmount to $SERVER_GS_RANDOM_SPAWNER_AMOUNT"
    echo "$(jq --arg name "$SERVER_GS_RANDOM_SPAWNER_AMOUNT" '.gameSettings.randomSpawnerAmount = $name' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_MINING_DAMAGE_FACTOR" ]]; then
    debug "updating gameSettingsMiningDamageFactor to $SERVER_GS_MINING_DAMAGE_FACTOR"
    echo "$(jq --argjson factor "$SERVER_GS_MINING_DAMAGE_FACTOR" '.gameSettings.miningDamageFactor = $factor' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_PLANT_GROWTH_SPEED_FACTOR" ]]; then
    debug "updating gameSettingsPlantGrowthSpeedFactor to $SERVER_GS_PLANT_GROWTH_SPEED_FACTOR"
    echo "$(jq --argjson factor "$SERVER_GS_PLANT_GROWTH_SPEED_FACTOR" '.gameSettings.plantGrowthSpeedFactor = $factor' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_RESOURCE_DROP_STACK_AMOUNT_FACTOR" ]]; then
    debug "updating gameSettingsResourceDropStackAmountFactor to $SERVER_GS_RESOURCE_DROP_STACK_AMOUNT_FACTOR"
    echo "$(jq --argjson factor "$SERVER_GS_RESOURCE_DROP_STACK_AMOUNT_FACTOR" '.gameSettings.resourceDropStackAmountFactor = $factor' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_FACTORY_PRODUCTION_SPEED_FACTOR" ]]; then
    debug "updating gameSettingsFactoryProductionSpeedFactor to $SERVER_GS_FACTORY_PRODUCTION_SPEED_FACTOR"
    echo "$(jq --argjson factor "$SERVER_GS_FACTORY_PRODUCTION_SPEED_FACTOR" '.gameSettings.factoryProductionSpeedFactor = $factor' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_PERK_UPGRADE_RECYCLING_FACTOR" ]]; then
    debug "updating gameSettingsPerkUpgradeRecyclingFactor to $SERVER_GS_PERK_UPGRADE_RECYCLING_FACTOR"
    echo "$(jq --argjson factor "$SERVER_GS_PERK_UPGRADE_RECYCLING_FACTOR" '.gameSettings.perkUpgradeRecyclingFactor = $factor' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_PERK_COST_FACTOR" ]]; then
    debug "updating gameSettingsPerkCostFactor to $SERVER_GS_PERK_COST_FACTOR"
    echo "$(jq --argjson factor "$SERVER_GS_PERK_COST_FACTOR" '.gameSettings.perkCostFactor = $factor' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_EXPERIENCE_COMBAT_FACTOR" ]]; then
    debug "updating gameSettingsExperienceCombatFactor to $SERVER_GS_EXPERIENCE_COMBAT_FACTOR"
    echo "$(jq --argjson factor "$SERVER_GS_EXPERIENCE_COMBAT_FACTOR" '.gameSettings.experienceCombatFactor = $factor' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_EXPERIENCE_MINING_FACTOR" ]]; then
    debug "updating gameSettingsExperienceMiningFactor to $SERVER_GS_EXPERIENCE_MINING_FACTOR"
    echo "$(jq --argjson factor "$SERVER_GS_EXPERIENCE_MINING_FACTOR" '.gameSettings.experienceMiningFactor = $factor' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_EXPERIENCE_EXPLORATION_QUESTS_FACTOR" ]]; then
    debug "updating gameSettingsExperienceExplorationQuestsFactor to $SERVER_GS_EXPERIENCE_EXPLORATION_QUESTS_FACTOR"
    echo "$(jq --argjson factor "$SERVER_GS_EXPERIENCE_EXPLORATION_QUESTS_FACTOR" '.gameSettings.experienceExplorationQuestsFactor = $factor' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_AGGRO_POOL_AMOUNT" ]]; then
    debug "updating gameSettingsAggroPoolAmount to $SERVER_GS_AGGRO_POOL_AMOUNT"
    echo "$(jq --arg name "$SERVER_GS_AGGRO_POOL_AMOUNT" '.gameSettings.aggroPoolAmount = $name' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_ENEMY_DAMAGE_FACTOR" ]]; then
    debug "updating gameSettingsEnemyDamageFactor to $SERVER_GS_ENEMY_DAMAGE_FACTOR"
    echo "$(jq --argjson factor "$SERVER_GS_ENEMY_DAMAGE_FACTOR" '.gameSettings.enemyDamageFactor = $factor' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_ENEMY_HEALTH_FACTOR" ]]; then
    debug "updating gameSettingsEnemyHealthFactor to $SERVER_GS_ENEMY_HEALTH_FACTOR"
    echo "$(jq --argjson factor "$SERVER_GS_ENEMY_HEALTH_FACTOR" '.gameSettings.enemyHealthFactor = $factor' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_ENEMY_STAMINA_FACTOR" ]]; then
    debug "updating gameSettingsEnemyStaminaFactor to $SERVER_GS_ENEMY_STAMINA_FACTOR"
    echo "$(jq --argjson factor "$SERVER_GS_ENEMY_STAMINA_FACTOR" '.gameSettings.enemyStaminaFactor = $factor' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_ENEMY_PERCEPTION_RANGE_FACTOR" ]]; then
    debug "updating gameSettingsEnemyPerceptionRangeFactor to $SERVER_GS_ENEMY_PERCEPTION_RANGE_FACTOR"
    echo "$(jq --argjson factor "$SERVER_GS_ENEMY_PERCEPTION_RANGE_FACTOR" '.gameSettings.enemyPerceptionRangeFactor = $factor' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_BOSS_DAMAGE_FACTOR" ]]; then
    debug "updating gameSettingsBossDamageFactor to $SERVER_GS_BOSS_DAMAGE_FACTOR"
    echo "$(jq --argjson factor "$SERVER_GS_BOSS_DAMAGE_FACTOR" '.gameSettings.bossDamageFactor = $factor' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_BOSS_HEALTH_FACTOR" ]]; then
    debug "updating gameSettingsBossHealthFactor to $SERVER_GS_BOSS_HEALTH_FACTOR"
    echo "$(jq --argjson factor "$SERVER_GS_BOSS_HEALTH_FACTOR" '.gameSettings.bossHealthFactor = $factor' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_THREAT_BONUS" ]]; then
    debug "updating gameSettingsThreatBonus to $SERVER_GS_THREAT_BONUS"
    echo "$(jq --argjson factor "$SERVER_GS_THREAT_BONUS" '.gameSettings.threatBonus = $factor' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_PACIFY_ALL_ENEMIES" ]]; then
    debug "updating gameSettingsPacifyAllEnemies to $SERVER_GS_PACIFY_ALL_ENEMIES"
    echo "$(jq --argjson bool "$SERVER_GS_PACIFY_ALL_ENEMIES" '.gameSettings.pacifyAllEnemies = $bool' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_TAMING_STARTLE_REPERCUSSION" ]]; then
    debug "updating gameSettingsTamingStartleRepercussion to $SERVER_GS_TAMING_STARTLE_REPERCUSSION"
    echo "$(jq --arg name "$SERVER_GS_TAMING_STARTLE_REPERCUSSION" '.gameSettings.tamingStartleRepercussion = $name' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_DAY_TIME_DURATION" ]]; then
    debug "updating gameSettingsDayTimeDuration to $SERVER_GS_DAY_TIME_DURATION"
    echo "$(jq --argjson factor "$SERVER_GS_DAY_TIME_DURATION" '.gameSettings.dayTimeDuration = $factor' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_NIGHT_TIME_DURATION" ]]; then
    debug "updating gameSettingsNightTimeDuration to $SERVER_GS_NIGHT_TIME_DURATION"
    echo "$(jq --argjson factor "$SERVER_GS_NIGHT_TIME_DURATION" '.gameSettings.nightTimeDuration = $factor' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_GS_TOMBSTONE_MODE" ]]; then
    debug "updating gameSettingsTombstoneMode to $SERVER_GS_TOMBSTONE_MODE"
    echo "$(jq --arg name "$SERVER_GS_TOMBSTONE_MODE" '.gameSettings.tombstoneMode = $name' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi
}
