#!/bin/bash
. "$(dirname "$0")/common"
. "$(dirname "$0")/defaults"
. "$(dirname "$0")/enshrouded-bootstrap-shared"

main() {
  info "Running enshrouded-bootstrap"
  prepareEnshroudedAppFolders
  updateOrCreateEnshroudedServerConfig
  prepareSteamA2sPythonLibrary
  bootstrapHook

  bootstrapWine

  initCrontab
  supervisorctl start enshrouded-updater
  info "Bootstrap complete"
}

bootstrapWine() {
  info "bootstrap wine"
  export WINEPREFIX=$WINEPREFIX
  export WINEARCH=$WINEARCH
  export WINEPATH=$WINEPATH
  export WINEDEBUG=$WINEDEBUG

  debug "winecfg"
  winecfg -v win10 >/dev/null 2>&1
  debug "wineboot"
  wineboot --init >/dev/null 2>&1

  info "wine version: $(wine64 --version)"

  info "wine bootstrap finished"
}

main
