#!/bin/bash
. "$(dirname "$0")/common"
. "$(dirname "$0")/defaults"

main() {
  apply_permissions
  setup_syslog
  exec /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
}

# Apply user id and group id
apply_permissions() {
  info "Setting uid:gid of enshrouded to $PUID:$PGID"
  groupmod -g "${PGID}" -o enshrouded
  usermod -u "${PUID}" -o enshrouded
  sed -i -E "s/^(enshrouded:x):[0-9]+:[0-9]+:(.*)/\\1:$PUID:$PGID:\\2/" /etc/passwd

  chown -R enshrouded:enshrouded \
    /opt/enshrouded \
    /home/enshrouded \
    /var/run/enshrouded

  if [[ "$SERVER_SAVE_DIR" == /* ]]; then
    debug "Setting permissions for $SERVER_SAVE_DIR"
    chown -R enshrouded:enshrouded "$SERVER_SAVE_DIR"
  fi

  if [[ "$SERVER_LOG_DIR" == /* ]]; then
    debug "Setting permissions for $SERVER_LOG_DIR"
    chown -R enshrouded:enshrouded "$SERVER_LOG_DIR"
  fi

  chgrp enshrouded /etc/supervisor/supervisord.conf
}

# Configure syslog
setup_syslog() {
  info "Setting up syslogd - logging to stdout"

  cat >/etc/rsyslog.d/stdout.conf <<EOF
\$FileOwner root
\$FileGroup root
\$PrivDropToUser root
\$PrivDropToGroup root

\$template custom,"%timegenerated:1:10:date-rfc3339% %timegenerated:12:23:date-rfc3339% %syslogtag%%msg:::sp-if-no-1st-sp%%msg:::drop-last-lf%\n"
\$ActionFileDefaultTemplate custom

*.*;cron,auth,authpriv.none /proc/self/fd/1          # send everything to stdout
EOF

  cat >"$supervisor_syslog_conf" <<EOF
[program:rsyslogd]
user=root
environment=HOME="/root",USER="root",LANG="en_US.UTF-8",PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
command=/usr/sbin/rsyslogd -n
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autostart=true
autorestart=true
priority=10
EOF
}

main
