#!/bin/bash
. "$(dirname "$0")/common"
. "$(dirname "$0")/defaults"

main() {
  info "Running enshrouded-bootstrap"
  prepareEnshroudedAppFolders
  updateOrCreateEnshroudedServerConfig
  initCrontab
  bootstrapWine
  supervisorctl start enshrouded-updater
  info "Bootstrap complete"
}

prepareEnshroudedAppFolders() {
  mkdir -p "$install_path"
}

bootstrapWine() {
  info "bootstrap wine"
  export WINEPREFIX=$WINEPREFIX
  export WINEARCH=$WINEARCH
  export WINEPATH=$WINEPATH
  export WINEDEBUG=$WINEDEBUG

  debug "winecfg"
  winecfg -v win10 >/dev/null 2>&1
  debug "wineboot"
  wineboot --init >/dev/null 2>&1

  info "wine version: $(wine64 --version)"

  info "wine bootstrap finished"
}

initCrontab() {
  crontab=$(mktemp)

  if [ -n "$UPDATE_CRON" ]; then
    debug "creating cron for update checks (schedule: $UPDATE_CRON)"
    echo "$UPDATE_CRON supervisorctl start enshrouded-updater >/dev/null 2>&1" >>"$crontab"
  fi

  crontab "$crontab"
  rm -f "$crontab"
}

updateOrCreateEnshroudedServerConfig() {
  if [[ ! -e ${install_path}/enshrouded_server.json ]]; then
    mkdir -p ${install_path}
    touch ${install_path}/enshrouded_server.json

    # write json to file ${install_path}/enshrouded_server.json

    cat >${install_path}/enshrouded_server.json << EOF
{
  "name": "Enshrouded Server",
  "password": "",
  "saveDirectory": "./savegame",
  "logDirectory": "./logs",
  "ip": "0.0.0.0",
  "gamePort": 15636,
  "queryPort": 15637,
  "slotCount": 16
}
EOF
  fi

  if [[ -n "$SERVER_NAME" ]]; then
    echo "$(jq --arg name "$SERVER_NAME" '.name = $name' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_PASSWORD" ]]; then
    echo "$(jq --arg password "$SERVER_PASSWORD" '.password = $password' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_SAVE_DIR" ]]; then
    echo "$(jq --arg saveDirectory "$SERVER_SAVE_DIR" '.saveDirectory = $saveDirectory' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_LOG_DIR" ]]; then
    echo "$(jq --arg logDirectory "$SERVER_LOG_DIR" '.logDirectory = $logDirectory' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_IP" ]]; then
    echo "$(jq --arg ip "$SERVER_IP" '.ip = $ip' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_PORT" ]]; then
    echo "$(jq --arg gamePort "$SERVER_PORT" '.gamePort = $gamePort' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_QUERYPORT" ]]; then
    echo "$(jq --arg queryPort "$SERVER_QUERYPORT" '.queryPort = $queryPort' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi

  if [[ -n "$SERVER_SLOT_COUNT" ]]; then
    echo "$(jq --arg slotCount "$SERVER_SLOT_COUNT" '.slotCount = $slotCount' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json
  fi
}

main
